services:
  php-apache-environment:
    container_name: php-apache-ci
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    working_dir: /var/www/html
    command: /bin/bash -c "composer install --no-interaction --no-plugins --no-scripts --no-dev --prefer-dist -vvv && apache2-foreground"
    ports:
      - 7700:80
  db:
    container_name: db-ci
    # image: mysql:5.7
    image: mariadb:10.5
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nano_password
      MYSQL_DATABASE: egitim
      MYSQL_USER: user1
      MYSQL_PASSWORD: nano_pass1
    ports:
      - 3310:3306
  phpmyadmin:
    container_name: phpmyadmin-ci
    image: phpmyadmin/phpmyadmin
    ports:
      - '8080:80'
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db
